### ISSUE TITLE
Legend of 'NajafabadiEtAl2017'

### ISSUE THREAD

**Issue by pixuenan** [jbkinney/logomaker#10]
Hi, Is there a way by which I can get a legend of color scheme 'NajafabadiEtAl2017', to present the meaning of each color?

**Comment by atareen** [comment]
Hi, have you seen this already?
https://logomaker.readthedocs.io/en/latest/examples.html#color-schemes

**Comment by atareen** [comment]
Did the above help?

**Comment by pixuenan** [comment]
Hi, atareen

Thanks. I saw the page you post above. I mean legend like

![image](https://user-images.githubusercontent.com/8290469/79524942-55ba2880-8094-11ea-9438-39a0858ff6d6.png)

This legend is simply from my guess.

I read the paper 'NajafabadiEtAl2017' extracted from but did not find the legend.

**Comment by atareen** [comment]
If I run the following, I get the color dictionary for the characters in NajafabadiEtAl2017.

`logomaker.src.colors.get_color_dict('NajafabadiEtAl2017',chars='A')`

I am not sure what your legend really means. E.g. Hydrophobic isn't once color. Anyway, using the rgb values that you get from running 'get_color_color' you can make the legend. 

I've attached a screenshot of what the code produces. 

![Screenshot 2020-04-18 15 28 12](https://user-images.githubusercontent.com/6977064/79669464-a3fd2380-8189-11ea-9cc8-a3a580684f95.png)

-Ammar

**Comment by atareen** [comment]
Did the above give you the information you need?

**Comment by pixuenan** [comment]
Hi atareen,

To get the legend, I just would like to know what does each color in the color scheme means? For example, why M and L is in color blue and K is in color red?

**Comment by atareen** [comment]
The colors were chosen simply replicate the color scheme in this paper: Najafabadi HS, et al. (2017). Non-base-contacting residues enable kaleidoscopic evolution of metazoan C2H2 zinc finger DNA binding. Genome Biol. 18(1):1–15.

**Comment by atareen** [comment]
The color scheme isn’t intended, at least by us, to illustrate the chemistry of individual amino acids, such as charge or hydrophobicity. It's simply to illustrate a feature of logomaker.
