### ISSUE TITLE
Allow_nan=True issue

### ISSUE THREAD

**Issue by ChenddatHKU** [jbkinney/logomaker#11]
Hi, 

Thanks so much for developing and sharing such good software.
But sometime, the matrix-like array is not intact, with some values missing and represented as NaN in pandas data frame.
the software remind to add allow_nan=True, but may I ask which statement shall I add? 

Thanks

**Comment by atareen** [comment]
Hello,

We actually removed the allow_nan keyword parameter (and its functionality) from logomaker’s Logo constructor; the message you’re seeing is a print statement left over from a unit-test/check related to the former allow_nan keyword, from the validate method. Sorry about the confusion.

What we are doing now is simply using pandas’ `fillna` function on input dataframes to handle nan entries. Hope this helps. 

Ammar

**Comment by ChenddatHKU** [comment]
Hi Ammar,

Thanks so much for your explanation. Question solved.
I could draw plots after 'fillna with 0', or fill with an extremely small values.

Best regards,
Dongdong
