### ISSUE TITLE
Development install

### ISSUE THREAD

**Issue by bsipos** [jbkinney/logomaker#12]
Hello!

Given the slightly unusual package layout, how can I install logomaker in development mode (eqivalent of `python setup.py develop`).

Thanks!

**Comment by atareen** [comment]
Hi Botond, 

There are multiple of ways to do this:

1. Clone the logomaker github repo to a local directory, cd into the repo directory and install logomaker requirements using pip, i.e.:  `pip install -r readthedocs_requirements.txt` (make sure you're in the correct directory by checking if the file 'readthedocs_requirements.txt' exists there). You should then be able to import logomaker package directory from the directory. Changes to the logomaker source should be picked up by python scripts. If you're using a jupyter notebook, you'll have to restart the kernel to see changes to source. 

2. You can install logomaker from PyPI by running `pip install logomaker` to a site packages directory, e.g., by specifying the `--user` flag with the pip install (or any local directory of your choice using install option), and then then insert the path of the package in the sys module. An example code snippet doing this would look like this:

```
# Insert logomaker path to sys.path
import sys 
sys.path.insert(0, absolute_path_to_directory_containing_logomaker)

import logomaker
```

3. virtualenv is also another reasonable option, especially if you don't want pip to interfere with existing packages installed on your machine. 

I am assuming you'd like to do development on a local machine. I have tried all of these methods on macOS and linux. Some of these solutions will still be possible for cloud based python (like google colab) but may require extra steps. 

Hope this helps.
-Ammar

**Comment by bsipos** [comment]
Thanks a lot, that answers my question!
