### ISSUE TITLE
How to make it run for kmers ('AA', 'AT', etc) instead of single letters('A', 'T')? 

### ISSUE THREAD

**Issue by PartheshSoni** [jbkinney/logomaker#13]
I basically want to find a sequence motif, taking into consideration kmers (length can be anything between 1 and maybe 5, 6), instead of single characters. So, I want to find the frequency of kmer at each position. Any idea how I can do that, using logomaker, or any other library?

**Comment by atareen** [comment]
Hi, 

You can do this using logomaker's Glyph class. You'll have to define custom gylph's for your task. I'm attaching a very barebones example which you could automate. Sample output attached.

![Screen Shot 2021-03-08 at 7 58 19 AM](https://user-images.githubusercontent.com/6977064/110324558-254ce700-7fe4-11eb-9e8b-ebc5f59aee30.png)


```
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline
plt.ion()

import logomaker
from logomaker import Glyph 
```

```
fig, ax = plt.subplots(figsize=[7,3])
# set bounding box
ax.set_xlim([0,2.5])
ax.set_ylim([0,1])

Glyph(c='AA', 
      p=0.5, 
      width= 1.0, 
      alpha=.85, 
      ax = ax,
      ceiling=0.2,
      floor=0.05, color='red')

Glyph(c='GG', 
      p=0.5, 
      width= 1.0, 
      alpha=.85, 
      ax = ax,
      ceiling=0.5,
      floor=0.25, color='Blue')

Glyph(c='GT', 
      p=1.75, 
      width= 1.0, 
      alpha=.85, 
      ax = ax,
      ceiling=0.8,
      floor=0.05, color ='green')

Glyph(c='CC', 
      p=1.75, 
      width= 1.0, 
      alpha=.85, 
      ax = ax,
      ceiling=1.0,
      floor=0.8, color ='black')
```

**Comment by atareen** [comment]
Hi, 

There's isn't a way to do this directly in logomaker, but what I can suggest is the following: you can modify the function alignmnet_to_matrix in logomaker to give you counts of multiple characters at a position, as in your task. I've pasted a link to the method below. If you do it this way, I think you'll have to update the loop starting on line 582. Once you have an updated dataframe, you can draw it with logomaker. 

https://github.com/jbkinney/logomaker/blob/76aae02e03af9a5abc0880054d7d0c9a6f571c07/logomaker/src/matrix.py#L467

During development we wrote methods for drawing dinucleotide logos (e.g., see below) but these currently aren't implemented. I hope this helps. I am not sure about other libraries.

![Screen Shot 2021-03-08 at 8 34 35 AM](https://user-images.githubusercontent.com/6977064/110328371-46fc9d00-7fe9-11eb-92ac-85ba40f5fd0b.png)

**Comment by PartheshSoni** [comment]
Thanks, that makes sense. But I am giving dataframes to Logo class, which contains cols as multi-letter strings and I am getting exception that multi-letters are not supported. Removing that exception clause and some other related clauses, I am able to plot as required but then the color of the letters is in grayscale. To resolve this, I am passing a dict containing color scheme (letter->color mapping dict), and removing the _expand_color_dict(), I am able to solve the issue.

**Comment by atareen** [comment]
Great, I'll close the issue.
