### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by chemgeeklian** [jbkinney/logomaker#17]
Hi, I have installed logomaker from pip. But whenever I `import logomaker` in my jupyter notebook, the kernel will die. And when I `import logomaker` in python command line, it outputs `Segmentation fault: 11`, and ends my process.

My python version is Python 3.7.4, the operating system is macOS Big Sur.

Thank you if you could take a look!

**Comment by atareen** [comment]
Hi, I think this issue may be specific to Big Sur and python 3.7 and not an issue with logomaker itself. Are you able to import matplotlib? Can you try importing logomaker in a different version of python, perhaps in a virtualenv? It will be possible to isolate the issue that way. Let me know.

**Comment by chemgeeklian** [comment]
Thank you, yes, I can import matplotlib in python 3.7. And seems python 3.7 is the issue. I successfully imported logomaker in python 3.9.
