### ISSUE TITLE
Rewriting of sequence logo object into pyplot object

### ISSUE THREAD

**Issue by Linesandvad** [jbkinney/logomaker#21]
Hi LogoMaker team,

Thank you for a very nice library! I am working on a website using the python library Streamlit. On this website, I am displaying sequence logos using LogoMaker. Producing a logo, I saw it is of the class 'logomaker.src.Logo.Logo'. However, this class is not compatible with a display on Streamlit, and with the purpose of what I am doing, I do not have the option of saving the figure as an image and then display that image to Streamlit. My question is thus, whether there is a way to turn the Sequence logos I produce with LogoMaker of the class 'logomaker.src.Logo.Logo' into a pyplot object directly? 

Thank you in advance!

Best,
Line

**Comment by atareen** [comment]
Hi, 

Have you tried using the fig attribute in a logo? e.g. 
`logo = logomaker.Logo(...)`
`logo.fig` <- this should be a matplotlib object.

This logo object should also have a matplotlib axis attribute, i.e., logo.ax, that you may be able to use. I used logomaker on a flask server to plot logos and it was straight forward, but I haven't used streamlit yet. Let me know how it goes and I'll look into it more.

Ammar

**Comment by atareen** [comment]
Were you able to try the above?

**Comment by Linesandvad** [comment]
Hi,

Thank you for the answer. I actually found another solution in the meantime (using in-memory storage to convert the logo into an image), but I just tested this and it worked too! Will definitely go with this solution from now on.

Best,
Line
