### ISSUE TITLE
Split sequences to generate multiple logo subplots

### ISSUE THREAD

**Issue by AngelRuizMoreno** [jbkinney/logomaker#24]
Hi, 

I have been testing the logomaker tool, and it's really handy and amazing. However, I am wondering if there's a parameter/way to split the logo into subplots when the sequence length is larger than X value. 

I noticed that other tools (mostly web servers) have the option to split the plots.

Thanks in advance for your assistance.

**Comment by atareen** [comment]
Hi, 

Logomaker objects can only be made from sequences of the same length. I'll need to see an example of what you're trying to do, but based on your comment, you could try to incorporate sequences of different lengths using gap characters (e.g., '-'), and subsequently use logomaker, but this would this require some manual scripting. If you could give me a simple example of what you'd like, that would be helpful. 

Thanks

**Comment by AngelRuizMoreno** [comment]
Hi @atareen,

Thank you for your quick answer.

I have a sequence alignment of 8 sequences with 370 residues each. I wanted to generate the logo using 50 residues each time. Since I didn't find an option to automatically split the sequence into chunks of 50 residues each, I generated the following workflow:

```
import logomaker as logomaker

def Chunk_list(lst,chunk_size):
    chunked_list = list()
    for i in range(0, len(lst), chunk_size):
        chunked_list.append(lst[i:i+chunk_size])
    return chunked_list

### Im using BioPython to handle my sequences aligment

alignment = AlignIO.read(f"data/Trees/test.aln", "fasta")     ### This is the file with my aligment ( 8 seqs with 370 residues each)

### This generates a dictionary containing the index as key and the sequences as values of a list
chunks={}
for seq in alignment:
    sequence_chunks=Chunk_list(str(seq.seq),50)
    for index,seq_fragment in enumerate(sequence_chunks):
        chunks.setdefault(index, []).append(seq_fragment)

### This makes the subplots, where each subplot is the aligment of the chunks

fig, axes = plt.subplots(nrows = len(chunks), ncols=1,figsize=(16,3*len(chunks)))
         
for index,seqs in chunks.items():
    ax=axes.ravel()[index]
    counts_mat=logomaker.alignment_to_matrix(sequences=seqs,to_type='counts', characters_to_ignore='.-X')
    logo=logomaker.Logo(counts_mat,shade_below=.5,fade_below=.5,color_scheme='charge',ax=ax,
                        #fade_probabilities=True,
                        stack_order='small_on_top')
    logo.style_spines(visible=False)
    logo.style_spines(spines=['left', 'bottom'], visible=True)
    logo.style_xticks(rotation=90,fmt='%d', anchor=0)
    logo.ax.set_ylabel("Bits", labelpad=-1)   
```
The code generates this plot:

![image](https://user-images.githubusercontent.com/34551143/180248020-10ed8082-9d21-4c13-9156-5e0519354c64.png)

I hope my explanation was clear. Would be nice to add the functionality to split the sequences in logo maker to generate the subplots for large sequences automatically.

Best wishes.

**Comment by atareen** [comment]
Hi again, I see what you're saying. My first thought was to propose exactly what you have done, i.e., write a custom script on top of logomaker to do this type of splitting. While I agree that auto-splitting would be a nice feature addition, I can't promise the addition of this feature, mostly due to time constraints. I'll take your feedback into consideration though. Thanks

**Comment by aspitaleri** [comment]
Hi,
I like to solution - is it possible to get sequential number, not starting from 0 every logo? Thanks
