### ISSUE TITLE
Start xticks at 1 instead of 0?

### ISSUE THREAD

**Issue by cossio** [jbkinney/logomaker#28]
In the examples in the docs, the positions are labeled starting at 0, a consequence of the peculiar way Python indexes arrays. But sequence positions are typically numbered starting from 1, not 0.

How can I get xtick labels starting from 1 instead of 0?

**Comment by atareen** [comment]
Hello! this can be done using the matplotlib functions that logomaker uses in the backend. Please refer to the splice sites logo example in the docs here https://logomaker.readthedocs.io/en/latest/examples.html#splice-site-probability-logo to see how you can set your ticklabels any way you want. Thanks
