### ISSUE TITLE
[IDEA] Is there a way to change the web logo background?

### ISSUE THREAD

**Issue by Jumitti** [jbkinney/logomaker#35]
Hello

As tittle says.. I don't find how to change background of weblogo..

So is this implemented and i don't see it or is not ?

Thank you :)

**Comment by atareen** [comment]
There are many tutorials and examples available to help achieve this. Please see:
https://logomaker.readthedocs.io/en/latest/examples.html#ars-enrichment-logo

Also please note that this is not web logo.
