### ISSUE TITLE
Saving figures

### ISSUE THREAD

**Issue by Russel88** [jbkinney/logomaker#4]
Thank you for a nice package.

Is it possible to save the plots as .pdf ?

Cheers,
Jakob

**Comment by atareen** [comment]
Hi Jakob, 

You can use matplotlib's `savefig` method to save logos in pdf, and in other formats. Here's a minimal example I just ran in a jupyter notebook:

`import logomaker as lm`
`import matplotlib.pyplot as plt`
`counts_mat = lm.get_example_matrix('crp_counts_matrix',print_description=False)`

`logo = lm.Logo(counts_mat)`
**`plt.savefig('logo.pdf')`**
`plt.show()`

Let me know if you have any issues saving. 
Best,
-Ammar

**Comment by Russel88** [comment]
Ah, great. Thank you!

**Comment by jbkinney** [comment]
No prob.

Cheers,
-Justin
{sent from my phone; please excuse typos}

   Justin B. Kinney
   Assistant Professor
   Simons Center for Quantitative Biology
   Cold Spring Harbor Laboratory
   jkinney@cshl.edu<mailto:jkinney@cshl.edu>
   631-897-5731


On May 14, 2019, at 09:20, Jakob Russel <notifications@github.com<mailto:notifications@github.com>> wrote:


Ah, great. Thank you!
