### ISSUE TITLE
Would you like assistance putting this up on conda-forge?

### ISSUE THREAD

**Issue by ericmjl** [jbkinney/logomaker#5]
I am wondering if conda-forge releases are on your roadmap? This would help simplify delivery of logomaker, which is a pretty awesome package.

Please let me know if you'd like any help with this. I've lost track of the number of packages I've helped get up on conda-forge, but it's not difficult, and there's lots of automation available once the package is up on conda-forge.

**Comment by jbkinney** [comment]
Hi Eric, thanks for the suggestion, and the offer of assistance. I think for now we're going to wait for comments from reviewers, but we may well do this once we finalize the software for publication.
