### ISSUE TITLE
Precision of alignment_to_matrix

### ISSUE THREAD

**Issue by bhwein** [jbkinney/logomaker#8]
The alignment_to_matrix(to_type="probability") function does not seem to produce precise values. When I expect a particular nucleobase to have a probability of 1 (every sequence has that base) it produces something more like 0.999228 with the other three bases producing values of 0.000256.

**Comment by atareen** [comment]
Hi, 

Please try pseudocount=0 when calling alignment_to_matrix. E.g., see https://github.com/jbkinney/logomaker/issues/6

**Comment by atareen** [comment]
Hi @bhwein, can you comment on whether this worked for you?

**Comment by bhwein** [comment]
@atareen This worked perfectly. Thank you!!
